### ISSUE TITLE
CSV parsing should support two double quotes

### ISSUE THREAD

**Issue by martindrapeau** [martindrapeau/csvjson-app#41]
According to [RFC-4180](https://tools.ietf.org/html/rfc4180), section 2.6, a nested double quote should be doubled. This test case fails currently:
https://www.csvjson.com/csv2json/0571e7604c0b937c40c90b9cec1b775c

**Comment by DrorHarari** [comment]
Martin,

I have merged your fixes and added supporting software section with a
reference to csvjson.com -- however, trying to put \" in one of the json
elements resulted in the output csv showing it as "" rather than \", even
though the checkbox to use the csvjson variant was checked.

Did I miss anything?

/d

**Comment by martindrapeau** [comment]
That was a bug now fixed. Please try again.

**Comment by DrorHarari** [comment]
Thanks, that works now. What about the other direction:

/d

**Comment by martindrapeau** [comment]
Its now live here:
https://www.csvjson.com/csvjson2json
