### ISSUE TITLE
JSON download button not working (converting from CSV to JSON)

### ISSUE THREAD

**Issue by preetiramaraj** [martindrapeau/csvjson-app#58]
https://www.csvjson.com/csv2json/0f7a56d45381e0428576da469abee125

**Comment by martindrapeau** [comment]
Here's the problem...
- The textarea contains too much text - its too big to create a download file.
- The UI is now showing that properly. There is a title on the button however since its disabled, it won't show on hover.
I'll fix the UI portion. In your case you can copy/paste instead.
![image](https://user-images.githubusercontent.com/104156/44586987-92c6fe00-a77f-11e8-8906-b712da6bcc10.png)

**Comment by martindrapeau** [comment]
It should now tell you
