### ISSUE TITLE
Cannot work functional with special letters

### ISSUE THREAD

**Issue by YizhiCatherineZhang** [martindrapeau/csvjson-app#68]
#### Instructions for filing an issue.
1. Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.

Here is the link: https://www.csvjson.com/csv2json/ba9e63656f06947df733a3bcc28af0ea

2. Describe your request.
Special letters like é, â  will become "?"

**Comment by th0rgall** [comment]
I'm experiencing a similar issue.

1. Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.
[https://csvjson.com/csv2json/0c7c38f7621773648b8f36ccabb5aeb8](https://csvjson.com/csv2json/0c7c38f7621773648b8f36ccabb5aeb8)

2. Describe your request.
On the site, the conversion between this csv with special characters __will work correctly__.
```
Test,bumba
lät,lelö
fúk,gał
```
will be converted to ```[
  {
    "Test": "lät",
    "bumba": "lelö"
  },
  {
    "Test": "fúk",
    "bumba": "gał"
  }
]```

However, when I *download* the .json multiple text editors on MacOS (Visual Studio Code, TextEdit) show the following:
```
[
  {
    "Test": "l‰t",
    "bumba": "lelˆ"
  },
  {
    "Test": "f˙k",
    "bumba": "ga%u0142"
  }
]
```
My workaround: a copy-paste instead of download.

**Comment by martindrapeau** [comment]
This problem is fixed. @YizhiCatherineZhang the input CSV of your example contains ? instead of accent letters. Can you try pasting again your CSV?

@th0rgall your test case works now. Thanks for reporting.
