### ISSUE TITLE
Arabic characters are not supported

### ISSUE THREAD

**Issue by salamwaddah** [martindrapeau/csvjson-app#77]
1. testcase: https://www.csvjson.com/csv2json/ac2395c526a8dc1773c6adedf46f89ff
2. When uploading a csv file with arabic characters, it's being escaped and converted into `__` character

Note: copying then pasting arabic content does NOT cause this issue to happen, only uploading a csv file causes this.

**Comment by DrorHarari** [comment]
Most likely the problem is that the CSV file you uploaded is encoded in ANSI (that is, Windows-1256 - https://en.wikipedia.org/wiki/Windows-1256) rather than in Unicode (UTF-8) so an Arabic character like Alif  'ا' arrives as 0xC7 without the information it is in Arabic and csvjson sees it as invalid UTF-8 character and replaces it with a replacement character (_). 

In WIndows, you can open the CSV file in Notepad and save it as UTF-8. Then you'll be able to upload it to csvjson and it will show Arabic just fine.
