### ISSUE TITLE
unicode characters on downloaded CSV (utf-8 not supported)

### ISSUE THREAD

**Issue by elbaza1** [martindrapeau/csvjson-app#78]
Link of the test case ::
https://www.csvjson.com/json2csv/df61580582fea1929d2c1ba50f5cfb8e

French Characters like 'é' are converted to 'Ã©' for example.
I suggest allowing 'utf-8' on download, or writing the csv files as 'utf-8' in the api before downloading
Thanks

**Comment by DrorHarari** [comment]
The download _is_ in UTF-8. The reason you see 'Ã©' is because the program you use (likely Excel or Wordpad) does not automatically recognize the data is in UTF-8 so the bytes 0xC3, 0xA9 are interpreted as two characters rather than the single character 'é'. Some other programs such as Notepad actually do recognize the file as UTF-8 and show the data fine.

You can ask why not automatically insert at the top of the file the BOM character (0xEF, 0xBB, 0xBF) which will make Excel, Wordpad and many other software products recognize the file as UTF-8?

The answer is that many CSV file processors actually balk at the BOM sequence at the beginning of the file and include it in the data where it looks like a garbage character. That is not universally the case and that is why, it may be useful to have another checkbox "Include BOM" to let the user ask for a BOM to be added.

![image](https://user-images.githubusercontent.com/1831901/61155463-b317bc80-a4f9-11e9-9776-58bceaf8dca4.png)

**Comment by martindrapeau** [comment]
I've gone ahead and added the BOM character at the beginning as I believe most people use this to work in Excel afterwards. If this becomes an issue, I can add the option.

**Comment by elbaza1** [comment]
Thank you @DrorHarari @martindrapeau  .

**Comment by jmappala** [comment]
HI.... I am having an error now. It has been working more than week ago.

I saved an iNav SQL data extract into CSV, then used CVSJSON to convert into JSON.

Run K6 to do praalel run, and got this: level=error msg="SyntaxError: invalid character 'ï' looking for beginning of value at parse (native)"

**Comment by jmappala** [comment]
FYI.... I used http://www.convertcsv.com/csv-to-json.htm, and it worked.

**Comment by martindrapeau** [comment]
Could you try again @jmappala? Should be fixed now.

**Comment by DrorHarari** [comment]
Adding the BOM automatically can break apps that do not expect it - the BOM would be seen as the first character of the first column name. If the app expects a specific column name, it would not find it (unless it expects the BOM). Hence while adding the BOM by default for the expected Excel audience, it may be safer to allow the user to request a CSV without it (via that checkbox). @martindrapeau - I understand you are waiting for that hypothetical person to stand up 😉, ok.

**Comment by jmappala** [comment]
@martindrapeau, and it worked.  Thanks.
